export const Formatting: { [key: string]: string } = {
	black: '§0',
	dark_blue: '§1',
	dark_green: '§2',
	dark_aqua: '§3',
	dark_red: '§4',
	dark_purple: '§5',
	gold: '§6',
	gray: '§7',
	dark_gray: '§8',
	blue: '§9',
	green: '§a',
	aqua: '§b',
	red: '§c',
	light_purple: '§d',
	yellow: '§e',
	white: '§f',
	bold: '§l',
	italic: '§o',
	underlined: '§n',
	strikethrough: '§m',
	obfuscated: '§k'
}